# COMPUTE
# hpc (bool):                whether the compute environment is local or hpc (disables certain GUI features)
# processors_per_job (int):  how many processors to allocate for each job (job step parallelization)
# max_job_workers (int):     how many maximum job workers at any time (job parallelization)
[compute]
hpc=true
processors_per_job=64
max_job_workers=6

# PARAMETERS
# name (name):  user-friendly name for the parameter
# id (str):     identifier for the parameter, cell for FreeCAD, paramater ID for OpenVSP (
# min (float):  minimum value for the parameter
# max (float):  maximum value for the parameter
[model]
[[model.parameters]]
name="Root Chord"
id="GFXAORPLFWH:WingGeom:XSec_1:Root_Chord"
min=0.625
max=1.50
[[model.parameters]]
name="Dihederal"
id="NJDEOYDFTRR:WingGeom:XSec_1:Dihedral"
min=-10
max=10

# OBJECTIVES
# name:  user-friendly name for the parameter
# id:    identifier for the objective, used during objective extraction 
# type:  whether the objective is to minimize or maximize its value
[optimizer]
[[optimizer.objectives]]
id="cd"
name="Cd"
type="minimize"
[[optimizer.objectives]]
id="cl"
name="Cl"
type="maximize"