[compute]
hpc=false
processors=8

[model]
# type: "freecad" | "openvsp"
type="freecad"
# linux
# freecad_path="/usr/lib/freecad/lib"
# macos
freecad_path="/Applications/FreeCAD.app/Contents/Resources/lib"
# windows
# freecad_path="C:\\Program Files\\FreeCAD\\bin"

# scale factor (1 mm -> 0.001 m)
scale_factor = 0.001

# DESIGN SPACE PARAMETERS
# name: user-friendly name for the parameter
# cell: cell corresponding to the cell in the FREECAD spreadsheet
# min: minimum value for the parameter
# max: maximum value for the parameter
[[model.parameters]]
name="Length"
cell="B1"
min=750
max=1000
[[model.parameters]]
name="Width"
cell="B2"
min=300
max=600

[optimizer]
population=20

[[optimizer.objective]]
name="Cd"
type="minimize"