[compute]
hpc=true
processors_per_job=64
max_job_workers=3

[model]
# DESIGN SPACE PARAMETERS
# name: user-friendly name for the parameter
# id: identifier for the parameter, cell for FreeCAD, paramater ID for OpenVSP
# min: minimum value for the parameter
# max: maximum value for the parameter
[[model.parameters]]
name="AoA"
id="VQYINKCPHJD:WingGeom:XForm:Y_Rel_Rotation"
min=-5
max=15

[optimizer]
[[optimizer.objectives]]
id="cd"
name="Cd"
type="minimize"
[[optimizer.objectives]]
id="cl"
name="Cl"
type="maximize"