[compute]
# hpc=false
processors=8

[model]
# DESIGN SPACE PARAMETERS
# name: user-friendly name for the parameter
# id: identifier for the parameter, cell for FreeCAD, paramater ID for OpenVSP
# min: minimum value for the parameter
# max: maximum value for the parameter
# [[model.parameter]]
# name="Length"
# id="B1"
# min=750
# max=1000
# [[model.parameter]]
# name="Width"
# id="B2"
# min=300
# max=600
[[model.parameter]]
name="Span"
id="VEBTFZANEQD:WingGeom:WingGeom:TotalSpan"
min=0.75
max=0.95
[[model.parameter]]
name="Chord"
id="MNGAFAQTAPA:WingGeom:WingGeom:TotalChord"
min=0.45
max=0.65
[[model.parameter]]
name="Sweep"
id="DFMNISRTXAJ:WingGeom:XSec_1:Sweep"
min=20
max=30
[[model.parameter]]
name="Dihedral"
id="NJDEOYDFTRR:WingGeom:XSec_1:Dihedral"
min=-10
max=10
# [[model.paramater]]
# name="Twist"
# id=
# min=-9
# max=0

[optimizer]
population=20

[[optimizer.objective]]
name="Cd"
type="minimize"