# COMPUTE
# hpc (bool):                whether the compute environment is local or hpc (disables certain GUI features)
# processors_per_job (int):  how many processors to allocate for each job (job step parallelization)
# max_job_workers (int):     how many maximum job workers at any time (job parallelization)
[compute]
hpc=true
processors_per_job=64
max_job_workers=20

# PARAMETERS
# name (name):  user-friendly name for the parameter
# id (str):     identifier for the parameter, cell for FreeCAD, paramater ID for OpenVSP (
# min (float):  minimum value for the parameter
# max (float):  maximum value for the parameter
[model]
[[model.parameters]]
name="Washout"
id="RCQFCVTUPMK:WingGeom:XSec_1:Twist"
min=-40
max=0
[[model.parameters]]
name="Angle of Attack"
id="AESEYMMNJRI:WingGeom:XForm:Y_Rel_Rotation"
min=-2
max=10
[[model.parameters]]
name="Sweep"
id="DFMNISRTXAJ:WingGeom:XSec_1:Sweep"
min=10
max=33
[[model.parameters]]
name="Airfoil Thickness"
id="BBGOGUGRFBF:WingGeom:XSecCurve_0:ThickChord"
min=0.07
max=0.3
[[model.parameters]]
name="Ground Height"
id="ground-height"
min=0.05
max=0.2

# OBJECTIVES
# name:  user-friendly name for the parameter
# id:    identifier for the objective, used during objective extraction 
# type:  whether the objective is to minimize or maximize its value
[optimizer]
[[optimizer.objectives]]
id="cd"
name="Cd"
type="minimize"
[[optimizer.objectives]]
id="cl"
name="Cl"
type="maximize"
[[optimizer.objectives]]
id="volume"
name="Volume"
type="minimize"