[compute]
# hpc=false
processors=8

[model]
# DESIGN SPACE PARAMETERS
# name: user-friendly name for the parameter
# id: identifier for the parameter, cell for FreeCAD, paramater ID for OpenVSP
# min: minimum value for the parameter
# max: maximum value for the parameter
# [[model.parameter]]
# name="Length"
# id="B1"
# min=750
# max=1000
# [[model.parameter]]
# name="Width"
# id="B2"
# min=300
# max=600
[[model.parameter]]
name="Span"
id="DGNZOEHYGLN:WingGeom:WingGeom:TotalSpan"
min=15
max=25
[[model.parameter]]
name="Chord"
id="PQIVTDAWZMG:WingGeom:WingGeom:TotalChord"
min=8
max=10
[[model.parameter]]
name="Sweep"
id="XGUXNKXLIKW:WingGeom:XSec_1:Sweep"
min=-10
max=10

[optimizer]
population=20

[[optimizer.objective]]
name="Cd"
type="minimize"