# COMPUTE
# hpc (bool):                whether the compute environment is local or hpc (disables certain GUI features)
# processors_per_job (int):  how many processors to allocate for each job (job step parallelization)
# max_job_workers (int):     how many maximum job workers at any time (job parallelization)
[compute]
hpc=false
processors_per_job=0
max_job_workers=0

# PARAMETERS
# name (name):  user-friendly name for the parameter
# id (str):     identifier for the parameter, cell for FreeCAD, paramater ID for OpenVSP (
# min (float):  minimum value for the parameter
# max (float):  maximum value for the parameter
[model]
[[model.parameters]]
name=""
id=""
min=0
max=0
[[model.parameters]]
name=""
id=""
min=0
max=0

# OBJECTIVES
# name:  user-friendly name for the objective
# id:    identifier for the objective, used during objective extraction 
# type:  whether the goal is to minimize or maximize the objective
[optimizer]
[[optimizer.objectives]]
name=""
id=""
type=""
[[optimizer.objectives]]
name=""
id=""
type=""